const productsData = [
  {
    name: "Classic Beef Burger",
    price: 8.99,
    category: "Food",
    image: "/assets/burger.png",
    stock: 45,
    description:
      "A juicy grilled beef patty served in a toasted bun with fresh lettuce, tomato, melted cheese, and special sauce — the perfect classic fast-food burger experience.",
    recent: true,
    sold: 120,
    rating: 4.6,
    tag: "popular",
  },
  {
    name: "Cheese Pizza Slice",
    price: 3.5,
    category: "Food",
    image: "/assets/pizza.png",
    stock: 100,
    description:
      "A generous slice of classic cheese pizza featuring stretchy mozzarella, tangy tomato sauce, and a golden crispy crust — simple, satisfying, and always delicious.",
    recent: false,
    sold: 340,
    rating: 4.7,
    tag: "bestseller",
  },
  {
    name: "Spicy Chicken Wings",
    price: 6.75,
    category: "Food",
    image: "/assets/turkey.png",
    stock: 60,
    description:
      "Crispy fried turkey wings (or chicken-style wings) tossed in a fiery hot sauce — bold, spicy, and perfect for heat lovers and game-day snacking.",
    recent: true,
    sold: 98,
    rating: 4.4,
    tag: "hot",
  },
  {
    name: "Fresh Red Apples",
    price: 2.99,
    category: "Fruit",
    image: "/assets/apples.png",
    stock: 200,
    description:
      "Crisp, juicy red apples with a perfect balance of sweetness and tartness — great for snacking, baking, or adding to fruit salads.",
    recent: false,
    sold: 410,
    rating: 4.8,
    tag: "healthy",
  },
  {
    name: "Organic Bananas",
    price: 1.89,
    category: "Fruit",
    image: "/assets/banana.png",
    stock: 180,
    description:
      "Ripe, sweet organic bananas full of natural energy and potassium — ideal for smoothies, cereal, baking, or eating straight as a healthy snack.",
    recent: false,
    sold: 520,
    rating: 4.9,
    tag: "organic",
  },
  {
    name: "Sweet Strawberries Pack",
    price: 4.25,
    category: "Fruit",
    image: "/assets/strawberries.png",
    stock: 90,
    description:
      "Vibrant, sweet, and juicy fresh strawberries — perfect for desserts, yogurt, smoothies, or enjoying fresh as nature's candy.",
    recent: true,
    sold: 130,
    rating: 4.6,
    tag: "fresh",
  },
  {
    name: "Crunchy Potato Chips",
    price: 2.5,
    category: "Snack",
    image: "/assets/coconut flakes.png",
    stock: 150,
    description:
      "Light, crispy toasted coconut flakes with a naturally sweet and nutty flavor — a healthy, crunchy alternative to traditional chips.",
    recent: false,
    sold: 600,
    rating: 4.3,
    tag: "snack",
  },
  {
    name: "Chocolate Chip Cookies",
    price: 3.99,
    category: "Snack",
    image: "/assets/crunchy nut.png",
    stock: 120,
    description:
      "Crunchy nut-filled cookies packed with roasted nuts and a touch of sweetness — perfect for a satisfying snack with great texture.",
    recent: true,
    sold: 275,
    rating: 4.7,
    tag: "sweet",
  },
  {
    name: "Salted Popcorn",
    price: 1.99,
    category: "Snack",
    image: "/assets/sahale.png",
    stock: 160,
    description:
      "Premium nut and fruit trail mix blend with a touch of sweetness and saltiness — a wholesome, satisfying snack for any time of day.",
    recent: false,
    sold: 340,
    rating: 4.2,
    tag: "light",
  },
  {
    name: "Mango Fruit Bowl",
    price: 3.75,
    category: "Fruit",
    image: "/assets/mango.png",
    stock: 70,
    description:
      "Fresh, ripe mango chunks bursting with tropical sweetness and juiciness — a refreshing and vitamin-rich fruit treat.",
    recent: true,
    sold: 150,
    rating: 4.6,
    tag: "tropical",
  },
  {
    name: "Grilled Chicken Sandwich",
    price: 7.25,
    category: "Food",
    image: "/assets/toast bread.png",
    stock: 55,
    description:
      "Toasted bread slices, perfect for making sandwiches, bruschetta, or enjoying with butter and spreads — simple, versatile, and freshly baked.",
    recent: false,
    sold: 190,
    rating: 4.5,
    tag: "lunch",
  },
  {
    name: "Grape Water",
    price: 2.8,
    category: "Beverage",
    image: "/assets/grape water.png",
    stock: 110,
    description:
      "Refreshing grape-flavored water — lightly sweetened with natural grape essence for a clean, fruity hydration experience.",
    recent: true,
    sold: 165,
    rating: 4.4,
    tag: "local",
  },
  {
    name: "Milk Jar",
    price: 3.1,
    category: "Dairy",
    image: "/assets/milk jar.png",
    stock: 140,
    description:
      "Fresh, creamy milk in a convenient jar — perfect for drinking, adding to cereal, coffee, baking, or enjoying cold.",
    recent: false,
    sold: 260,
    rating: 4.5,
    tag: "vitamin",
  },
  {
    name: "Pistachio",
    price: 2.95,
    category: "Snack",
    image: "/assets/pistachio.png",
    stock: 75,
    description:
      "Premium roasted pistachios with their signature nutty flavor and satisfying crunch — a nutritious and addictive snack.",
    recent: false,
    sold: 210,
    rating: 4.3,
    tag: "fastfood",
  },
  {
    name: "Macarroni",
    price: 4.6,
    category: "Food",
    image: "/assets/spag rolls.png",
    stock: 65,
    description:
      "Crispy fried spaghetti rolls (macaroni coated and deep-fried) — a popular crunchy, savory snack with great texture.",
    recent: true,
    sold: 145,
    rating: 4.7,
    tag: "healthy",
  },
  {
    name: "Water Melon",
    price: 1.75,
    category: "Fruit",
    image: "/assets/water melon.png",
    stock: 130,
    description:
      "Sweet and refreshing whole watermelon — incredibly hydrating with crisp, juicy red flesh perfect for hot days.",
    recent: false,
    sold: 390,
    rating: 4.4,
    tag: "energy",
  },
  {
    name: "Vegetable Salad",
    price: 2.35,
    category: "Food",
    image: "/assets/Vegetable salad.png",
    stock: 85,
    description:
      "Fresh mixed vegetable salad with crisp greens, colorful veggies, and a light dressing — healthy, crunchy, and full of nutrients.",
    recent: true,
    sold: 175,
    rating: 4.6,
    tag: "dessert",
  },
  {
    name: "Cocoa",
    price: 2.9,
    category: "Beverage",
    image: "/assets/cocoa.png",
    stock: 95,
    description:
      "Rich, warm cocoa drink made from premium cocoa powder — comforting, chocolatey, and perfect for cozy moments.",
    recent: false,
    sold: 305,
    rating: 4.5,
    tag: "pastry",
  },
  {
    name: "Watermelon Slices",
    price: 3.4,
    category: "Fruit",
    image: "/assets/water melon.png",
    stock: 80,
    description:
      "Juicy, seedless watermelon slices ready to enjoy — super refreshing, hydrating, and naturally sweet.",
    recent: true,
    sold: 160,
    rating: 4.6,
    tag: "refreshing",
  },
  {
    name: "Muffin",
    price: 4.15,
    category: "Bakery",
    image: "/assets/muffin.png",
    stock: 70,
    description:
      "Soft, fluffy muffin with a domed top — classic bakery goodness perfect for breakfast, snacks, or with coffee.",
    recent: false,
    sold: 230,
    rating: 4.4,
    tag: "party",
  },
];

console.log(productsData.filter((product) => product.recent));

fetch("http://localhost:3000/api/products", {
  method: "POST",
  headers: { "content-type": "application/json" },
  body: JSON.stringify(productsData),
})
  .then((res) => res.json())
  .then((data) => console.log(data));
